services:
  ollama:
    volumes:
      - ./ollama_data:/root/.ollama
    ports:
      - 11434:11434
    container_name: ollama
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
  ollama-webui:
    build:
      context: .
      args:
        OLLAMA_API_BASE_URL: '/ollama/api'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    depends_on:
      - ollama
    ports:
      - 3000:8080
    volumes:
      - ./webui_data:/app/backend/data
    environment:
      - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
